apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: teste
  name: teste
spec:
  containers:
  - image: nginx
    name: webserver
    resources: {}
    volumeMounts:
      - mountPath: /mnt/teste
        name: example-volume
  - image: debian
    name: debian
    command: ["sleep"]
    args: ["1800"]
    resources: {}
    volumeMounts:
      - mountPath: /mnt/teste
        name: example-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always

  volumes:
    - name: example-volume
      emptyDir:
        sizeLimit: 500Mi
status: {}
