apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: teste
  name: teste
spec:
  containers:
  - image: nginx
    name: webserver
    resources: {}
    volumeMounts:
      - mountPath: /etc/nginx/conf.d
        name: example-volume
        readOnly: true
  - image: httpd
    name: apache
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

  volumes:
    - name: example-volume
      # mount: ./nginx
      hostPath:
        path: ./nginx
status: {}
