apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv-nfs
  labels:
    the: chosen-one
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # only one pod is allow to read and write (per time?)
  persistentVolumeReclaimPolicy: Retain # if the pvc is deleted then retain the volume
  nfs:
    server: 192.168.1.105
    # server: host.docker.internal
    # server: 172.17.0.1
    path: /mnt/nfs
    readOnly: false
  # hostPath:
  #   path: /mnt/data
  storageClassName: giropops-nfs
