apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # only one pod is allow to read and write (per time?)
  persistentVolumeReclaimPolicy: Retain # if the pvc is deleted then retain the volume
  hostPath:
    path: /mnt/data
  storageClassName: custom-storage-class
