apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: giropops-nfs
provisioner: kubernetes.io/no-provisioner # default in kind
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  archiveOnDelete: "false"