apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-storage-class
provisioner: rancher.io/local-path # default in kind
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
