apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-exporter-daemonset
spec:
  selector:
    matchLabels:
      app: nginx-exporter-daemonset
  template:
    metadata:
      labels:
        app: nginx-exporter-daemonset
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.9.0
          ports:
            - containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
  