apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: webserver
          resources:
            requests:
              memory: 64Mi
              cpu: 0.3
            limits:
              memory: 128Mi
              cpu: 0.5
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort # assigns a IP on the cluster to the service
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 81 # exposed port
      targetPort: 80 # port in the pod
      nodePort: 30007
