apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  clusterIP: "None"
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  replicas: 3
  serviceName: nginx
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: webserver
          resources:
            requests:
              cpu: 0.3
              memory: 64Mi
            limits:
              cpu: 0.5
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-external-k8s-local
spec:
  type: ExternalName
  externalName: nginx-0.nginx.default.svc.cluster.local
