apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  clusterIP: "None" # must be None when is Headless
  ports:
    - port: 80
      name: http
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: webserver
          # volumeMounts:
          #   - name: html
          #     mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
              name: http # must match the service port name
  # volumeClaimTemplates:
  #   - metadata:
  #       name: html
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       storageClassName: standard
  #       resources:
  #         requests:
  #           storage: 1Gi

