apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list"]
  # - apiGroups: ["apps"]
  #   resources: ["deployments"]
  #   verbs: ["get,list"]
