apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
  namespace: dev
subjects:
  - kind: User
    name: developer
    # namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer
  # - apiGroup: rbac.authorization.k8s.io
  #   kind: User
  #   name: developer
    # namespace: dev