apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-role
rules:
  - apiGroups: [""]
    verbs: ["get", "list"]
    resources: ["pods"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-rolebinding
subjects:
  - kind: ServiceAccount
    name: custom-service-account
roleRef:
  kind: Role
  name: sa-role
