apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |+
    server {
        listen       80;
        listen       443 ssl;

        # listen  [::]:443 ssl;
        server_name  localhost;
        server_name         eduardothums.com;
        ssl_certificate     /etc/nginx/tls/certificate.crt;
        ssl_certificate_key /etc/nginx/tls/private-key.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /error.html;
        location = /error.html {
            root   /usr/share/nginx/html;
        }

    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |+
    <html>
      <h1>this matter will be solved accordingly</h1>
    </html>
  error.html: |+
    <html>
      <h1>you SHALL NOT PASS!!!</h1>
    </html>
immutable: True
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-https
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    
    spec:    
      volumes:
        - name: nginx-tls
          secret:
            secretName: eduardothums
            items:
              - key: tls.crt
                path: certificate.crt
              - key: tls.key
                path: private-key.key

        - name: nginx-conf
          configMap:
            name: nginx-conf

        - name: nginx-html
          configMap:
            name: nginx-html

      containers:
        - image: nginx
          name: webserver
          ports:
            - containerPort: 443
          volumeMounts:
            - name: nginx-tls
              mountPath: /etc/nginx/tls
            - name: nginx-conf
              mountPath:  /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-html
              mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-https
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 443