apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shell-pod
  name: shell-pod
spec:
  # volumes:
  #   - name: secret-volume
  #     secret:
  #       secretName: my-secret

  containers:
    - image: nginx
      name: shell-pod
      resources: {}  
      command:
        - env
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: username
      # volumeMounts:
      #   - name: secret-volume
      #     mountPath: /etc/secret-volume
      #     readOnly: true

  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: private-image
spec:
  containers:
    - image: eduardothums/private
      name: private-image
      resources: {}
  imagePullSecrets:
    - name: dockerhub-test

  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
