apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |+
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }

    server {
        listen       8080;
        server_name  localhost;

        location /metrics {
            stub_status;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webserver
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
      annotations: # without this annotations the prometheus cannot scrape the metrics even if the service monitor is enabled
        prometheus.io/scrape: 'true' # habilita o scraping do Prometheus
        prometheus.io/port: '9113' # porta do target
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf

      containers:
        - image: nginx
          name: nginx
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          ports:
            - containerPort: 80
              name: web
            - containerPort: 8080
              name: web-metrics
        - image: nginx/nginx-prometheus-exporter:1.4.2
          name: nginx-exporter
          args:
            - --nginx.scrape-uri=http://localhost:8080/metrics
          ports:
            - containerPort: 9113
              name: metrics
          resources:
            limits: 
              cpu: 0.5
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-webserver-svc
  labels:
    app: nginx
spec:
  ports:
    - port: 9113
      name: custom-metrics
  selector:
    app: nginx
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-webserver
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - interval: 20s
      path: /metrics
      targetPort: 9113
      
